/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.v7.appcompat;

public final class R {
    private R() {}

    public static final class anim {
        private anim() {}

        public static int abc_fade_in = 0x7f010001;
        public static int abc_fade_out = 0x7f010002;
        public static int abc_grow_fade_in_from_bottom = 0x7f010003;
        public static int abc_popup_enter = 0x7f010004;
        public static int abc_popup_exit = 0x7f010005;
        public static int abc_shrink_fade_out_from_bottom = 0x7f010006;
        public static int abc_slide_in_bottom = 0x7f010007;
        public static int abc_slide_in_top = 0x7f010008;
        public static int abc_slide_out_bottom = 0x7f010009;
        public static int abc_slide_out_top = 0x7f01000a;
        public static int abc_tooltip_enter = 0x7f01000b;
        public static int abc_tooltip_exit = 0x7f01000c;
    }
    public static final class attr {
        private attr() {}

        public static int actionBarDivider = 0x7f040002;
        public static int actionBarItemBackground = 0x7f040003;
        public static int actionBarPopupTheme = 0x7f040004;
        public static int actionBarSize = 0x7f040005;
        public static int actionBarSplitStyle = 0x7f040006;
        public static int actionBarStyle = 0x7f040007;
        public static int actionBarTabBarStyle = 0x7f040008;
        public static int actionBarTabStyle = 0x7f040009;
        public static int actionBarTabTextStyle = 0x7f04000a;
        public static int actionBarTheme = 0x7f04000b;
        public static int actionBarWidgetTheme = 0x7f04000c;
        public static int actionButtonStyle = 0x7f04000d;
        public static int actionDropDownStyle = 0x7f04000e;
        public static int actionLayout = 0x7f04000f;
        public static int actionMenuTextAppearance = 0x7f040010;
        public static int actionMenuTextColor = 0x7f040011;
        public static int actionModeBackground = 0x7f040012;
        public static int actionModeCloseButtonStyle = 0x7f040013;
        public static int actionM